version: '3'

services:
  ui:
    build: .
    image: sourcecheck/honorbox-ui
    container_name: honorbox-ui
    env_file: 
      - .env.build
      
networks:
  default:
    external:
      name: webproxy
